### ISSUE TITLE
fuckit.py screws up function calls within a namespace, hides errors

### ISSUE THREAD

**Issue by jvictor0** [ajalt/fuckitpy#28]
if you have  to_be_fucked.py
```
def foo():
    print "flipit"

def bar():
    foo()
    print "frickit"
```
and do, in another file
```
import fuckit
fuckit(fuckit(a))
a.bar()
```

it only prints `frickit`.
Closer examination shows that the call to `foo()` inside `bar()` is throwing `NameError: global name 'foo' is not defined`, which is being (correctly) swallowed by `fuckit`.  

I'm not good enough at the python `ast` stuff to figure out why on earth it would be doing it, but this issue is preventing me from using `fuckit.py` in production.

**Comment by ajalt** [comment]
> this issue is preventing me from using fuckit.py in production.

> using fuckit.py in production.

ಠ_ಠ

**Comment by ajalt** [comment]
Anyway, I fixed the issue, and may God have mercy on your soul.

**Comment by jvictor0** [comment]
Fix works.  
Fuckit, lets push this shit to prod a week before crampus!
