### ISSUE TITLE
Fails to import packages

### ISSUE THREAD

**Issue by chrisjbillington** [ajalt/fuckitpy#29]
Example:

```
main.py
some_shitty_package/
    __init__.py
````

```python
# main.py
import fuckit
module = fuckit('some_shitty_package')
print(module.x)
```

```python
# __init__.py
x = 7
raise Exception('package failed to import!')
```

Expected:

```
$ python3 main.py
7
```

Actual:
```python
$ python3 main.py
Traceback (most recent call last):
  File "main.py", line 2, in <module>
    module = fuckit('some_shitty_package')
  File "/home/cjb7/anaconda3/lib/python3.6/site-packages/fuckit.py", line 119, in __call__
    source = sourcefile.read()
AttributeError: 'NoneType' object has no attribute 'read'
```

Chaining doesn't help! The problem is that `imp.find_module` returns `None` for the file when the module to be imported is a package.

Also I like to think I have a genuine use case for `fuckit.py`. Basically a lot of my projects import each other initially to look at each other's `__version__` attribute, and cough exceptions if they are being used with incompatible versions of each other. Sometimes importing fails *because* the wrong version is being used, and it would be useful to be able to still read the version string and raise that exception first, because it can be completely opaque why the import is failing when really the problem is that you're using incompatible versions of things. So the program is going to fail anyway, and I would rather it fail with a more meaningful exception.

And whilst I could check versions using distutils and friends, actually importing the module and checking is more reliable, since if you have a poorly configured environment you might have dregs of old packages around reporting their version numbers to distutils even though a different version will be imported - and without getting the version exception it's hard to know that that's what the problem is.

But it's proved very difficult to get that version string out, even with `fuckit.py`! Something less violent would be fine, really all I want is the globals dict of the failed import, but this has proved extremely difficult and I probably won't bother. Nonetheless here's a bug report.

**Comment by chrisjbillington** [comment]
Aha! I see I have an out of date version of fuckit.py.

The present version doesn't crash, but neither does it manage to partially import the broken module. It doesn't realise it's a `imp.PKG_DIRECTORY` and that it could still execute it if it wanted to rather than falling back to the standard import mechanisms. 

I'll submit a pull request :)

**Comment by chrisjbillington** [comment]
Ah actually I give up - there's more work involved in supporting packages since the source manipulation would then have to look at submodules. So I don't care enough, since I don't care about the source code manipulation. But here's my solution in case you want to make fuckit.py work with more stuff:

```python
import sys
import os
import types
import imp
import marshal


def brute_import_fallback(victim):
    # No module code to execute? Just import the usual way then and return an
    # empty module upon exception:
    try:
        module = __import__(victim)
        return module, None
    except Exception:
        module = types.ModuleType(victim)
        return module, sys.exc_info()


def brute_import(victim):
    """Execute a module as if it were being imported, ignore exceptions, and
    return the (possibly only partially initialised) module object as well as
    the exc_info for the exception (or None if there were no exceptions)"""

    sourcefile, pathname, (_, _, module_type) = imp.find_module(victim)
    module = types.ModuleType(victim)
    sys.modules[victim] = module

    if module_type in [imp.PY_SOURCE, imp.PY_COMPILED]:
        module.__file__ = pathname
    elif module_type == imp.PKG_DIRECTORY:
        module.__path__ = [pathname]
        module.__file__ = os.path.join(pathname, '__init__.py')
        sourcefile = open(module.__file__)
    else:
        return fallback(victim)

    if module_type in [imp.PY_SOURCE, imp.PKG_DIRECTORY]:
        code = compile(sourcefile.read(), module.__file__, 'exec', dont_inherit=True)
    elif module_type == imp.PY_COMPILED:
        if sourcefile.read(4) != imp.get_magic():
            # Different python version, we can't execute:
            return fallback(victim)
        # skip timestamp:
        _ = sourcefile.read(4)
        code = marshal.load(sourcefile)
    else:
        # Some C extension or something. No code for us to execute.
        return fallback(victim)
        
    try:
        # Execute the module code in its namespace:
        exec(code, module.__dict__)
        return module, None
    except Exception:
        exc_info = sys.exc_info()
        return module, sys.exc_info()
```

**Comment by ajalt** [comment]
Thanks for the detailed issue, and your preliminary code! 

I don't expect that I'll implement the change, since it might encourage someone to actually use this library. 

> _Some people, when confronted with a problem in Python, think "I know, I'll use fuckit.py". Now they have **i̷̪̹͕̙̯̕͞n͏̠f̵͏̱̺̯͇̦͙̥i̴̢̠̗n̛̪̯͍̤̘̳̕͜ͅi҉͕̝͓͈̗̣t̸̛̻e̴̡̻̥ ̠̯͝p̛͙͇͔̗̩̜̘ͅr̨̹͉̺̝͕̜̲̣͘͞o̺͕̜͍̙̪͜͢͢b̧̨͙̼̠͜ĺ̤̘̲͇͔͘e͖̤ͅm̶̡̤s͉̥̻͉͓͖͜**._
