### ISSUE TITLE
Fucked code catches breakpoints in wrong locations.

### ISSUE THREAD

**Issue by SimLeek** [ajalt/fuckitpy#30]
I'm actually using this library at work, and it's pretty great. 

We have some old IronPython code, but nobody likes IronPython anymore, so instead of fixing mountains of old code to work with normal python, we just said fuck it.

It works for the most part, but there are a few pieces of code like:

`import someIronPythonShit`
`someIronPythonShit.open.dialogNoOneWantsToSee("fml")`

both of those lines would fail, and are satisfyingly steamrolled over with fuckit, but when I try to check breakpoints in thousands of lines of fucked IronPython code, PyCharm catches them in the wrong locations.

Looking at the code here though, it seems like it should be an easy fix. (No, it's not fuckit('fuckit')):

In line 138 in fuckit.py, we have ` del lines[lineno - 1]`. 
If we change that to `lines[lineno - 1] = ''`, it should work perfectly, hopefully...

...

...Actually, I just checked it with some of the code here. It did work perfectly! I might've even cried a few tears of 'I don't have to deal with this shit anymore'.

**Comment by ajalt** [comment]
> actually using this library 

ಠ_ಠ

**Comment by SimLeek** [comment]
Well, actually just for unit testing. It works pretty well for the setup...

I mean, it's definitely not an ideal setup, but solving that problem is hard.
